name: Deploy IPFS
# This workflow is triggered on pushes to the repository.$
on: [push]
jobs:
  build:
    name: Deploy
    # This job runs on Linux$
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build$
        run: ./parse-markdown.js 
      - name: IPFS Pinata deploy GitHub action
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.5.2
        with:
          pin-name: 'My personal site'
          path: './index.html'
          pinata-api-key: ${{ secrets.pinataKey }}
          pinata-secret-api-key: ${{secrets.pinataSecret }}
          verbose: true
